name: Deploy and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 1. Gerencia de forma totalmente automática a Tag, a Release e o Changelog
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

  # 2. Faz o deploy para o seu GitHub Pages atual
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o ambiente do Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos do Frontend (Raiz do projeto)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4